### PR TITLE
updating default seed

### PR DESCRIPTION
**Pull request by OKTurnbull**
Hi! Love the package, super useful :) 

I was testing it with some contrived probabilities with 5 states and found surprising results. I found this was due to the seeding. I was using n=20 so it was likely that for thousands of runs the seeds were the same resulting in weird results. The fix was to increase the "high" in numpy.random.randint. 

Lmk if you would prefer a different number or implementation. Thanks!

### CODE REVIEW

**Comment by maximtrp** [comment]
Interesting! Thank you! Haven't reviewed these lines for a long time.

**Comment by fountaindive** [comment]
Do you think you would be able a new release with this change? thanks!

**Comment by maximtrp** [comment]
@fountaindive @OKTurnbull Released the new version.

**Comment by fountaindive** [comment]
Thank you!

**Pull request merged**
