### PR TITLE
add threshold parameter to graph method

### PR DESCRIPTION
**Pull request by fountaindive**
This is a really awesome package! This PR adds a `p_thresh` parameter to the `graph_make` method of `mc`
so that you can avoid drawing links with zero probability.

I've found that this can help increase the readability of the figures.

Let me know if you have a better implementation idea!

### CODE REVIEW

**Comment by maximtrp** [comment]
Thank you!

**Comment by fountaindive** [comment]
Do you think you would be able to make a new release? Thanks!

**Comment by maximtrp** [comment]
The new version is out! @fountaindive

**Comment by fountaindive** [comment]
amazing thank you very much!

**Pull request merged**
